### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED for self-signed certs

### ISSUE THREAD

**Issue by sknop** [derlin/mantelo#12]
I get this error

requests.exceptions.SSLError: HTTPSConnectionPool(host='samba.bootcamp-london.confluent.io', port=8443): Max retries exceeded with url: /realms/master/protocol/openid-connect/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))

This is because my certificate is self-signed in my dev environment. The keycloak Python library has an extra flag for this

verify='/home/ubuntu/root-ca.pem'

Can you please add something similar like this to your library as well?

**Comment by derlin** [comment]
Hello @sknop and thank you for reaching out!

mantelo uses requests under the hood. You can set a custom CA bundle by customizing the session passed to the mantelo client. Here is an example using the username/password, but the same logic holds for other authentication methods:

```python
from mantelo import KeycloakAdmin
import requests

# Create the session and customize it as you like
# Note: the authentication part will be added by mantelo
session = requests.Session()
session.verify = "/path/to/ca-bundle.crt"  # or False to disable SSL verification

client = KeycloakAdmin.from_username_password(
    server_url="https://your.keycloak.url",  # base Keycloak URL
    realm_name="master",
    # ↓↓ Custom session
    session=session,  # <= here is the trick
    # ↓↓ Authentication
    client_id="admin-cli",
    username="admin",
    password="admin", 
)
```

More info can be found requests documentation [SSL Cert Verification](https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification).

Let me know if this works for you!

**Comment by sknop** [comment]
Yes, this works, thank you for the quick response.
