### ISSUE TITLE
I can't delete a user

### ISSUE THREAD

**Issue by tanrax** [derlin/mantelo#5]
I have tried using different filters:

By username:

```python
c.users.delete(username="foo")
```

By id:

```python
c.users.delete(id="4becede2-bdb6-46cb-b1f6-52726d3ce4f2")
```

And by email:

```python
c.users.delete(email="foo@boo.com")
```

In all cases I have received a 405. I also can't find examples. Keycloak docs say: DELETE /{realm}/users/{id}

It would be awesome if you had the repository examples to update and delete.

As an extra piece of information, I am logging in to master but I am deleting the user from another realm. I have no problems creating it.

PS: I love the repository ♥️. Both the design and the code itself.

**Comment by derlin** [comment]
Hi @tanrax and thank you for the kind words and the issue!

There is some examples in the [docs](https://mantelo.readthedocs.io/en/latest/02-making-calls.html) but I could indeed add more (thanks for the suggestion).

If the operation is `DELETE /{realm}/users/{id}`, then the expected call should look like:
```python
c.users("4becede2-bdb6-46cb-b1f6-52726d3ce4f2").delete()
```

What you pass to the `.delete` itself will only add *query parameters* (things after the `?`), not *path parameters*.
The ID of the user can be found by using `c.users.get(email="...")[0]["id"]` or other means.

I will add a note to add more examples to the documentation. Let me know if this works of if you need more pointers!

**Comment by tanrax** [comment]
It works perfectly. The issue is resolved for me.
Thank you very much for your work and attention! 😁
