### ISSUE TITLE
I can't delete Realm

### ISSUE THREAD

**Issue by tanrax** [derlin/mantelo#6]
I've been reviewing the documentation and the repository code and I don't understand why it doesn't work.
Keycloak needs `DELETE /{realm}`. If I'm not wrong, the equivalence would be.

```python
c.delete()
```

or

```python
c.delete("foo")
```

However, the base_url is `http://localhost:8080/admin/realms/foo/delete`. But it should be: `http://localhost:8080/admin/realms/foo/`.

Could it be a limitation of Slumber?

Thanks!!

**Comment by derlin** [comment]
Hello @tanrax,
Wow, that's indeed a bug you found here. The limitation lies within the mantelo implementation. Thanks for the report!

I should be able to provide a fix to interact with the realm itself (`/realms/{name}/` endpoints) using `client.get()`, `client.delete()`, etc. quickly. Does it sound good or do you have a better idea for dealing with realm endpoints?

**Comment by tanrax** [comment]
I like it, it seems like a good solution 😄
Would it break the structure to use the name `realm`? For example `c.realms.delete("foo")` or `c.realms.get()`? Just a suggestion to make it clearer in the code.

**Comment by derlin** [comment]
Hello again @tanrax ! I created a pull request with a first proposal. May I ask you to have a look and tell me what you think of it? Any suggestion is welcome :)

Thanks!

**Comment by tanrax** [comment]
In principle I have nothing more to add. I look forward to trying the new code :D
